 development:
      bucket: mindimp
      access_key_id: AKIAIVE5XD2EUTMKO7GA
      secret_access_key: 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

production:
      bucket: mindimp
      access_key_id: AKIAIVE5XD2EUTMKO7GA
      secret_access_key: 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

